### ISSUE TITLE
Add a hole dead center to the power supplies, **not in line** with the supplies mount hole

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/RobotInterfaceBoard#14]
I want to put a supporting block under the power supplies. I need a hole under the supply, **but not in line with the supplies hole**. This hole should be 3.1mm diameter. This block will have its own fastener, with a second fastener holding the supply. This will make the replacement easier and the assembly less fiddly.

**Comment by acamilo** [comment]
I don't understand this request. There is already a hole for a standoff under each supply module.

**Comment by madhephaestus** [comment]
the hole on the board is in line with the mount holes on the power supply. Not that, anywhere else but that

**Comment by acamilo** [comment]
I understand what but not why. what plan do you have for mounting the supplies? i was going to use a standoff and a screw.

**Comment by madhephaestus** [comment]
there will be a small printed block with a hole and countersunk head that mounts through the RBO to the case. the block will have a threaded hole that the supply mounts to. As it gets bumped over time the standoffs come loose (or are threadlocker and are hard to remove) and with a screw from below, would require disassembly of the case to tighten the screw again.

**Comment by acamilo** [comment]
I don't like this because it covers the chips. With a standoff we would have airflow.

**Comment by acamilo** [comment]
thoughts on something like this?
https://www.adafruit.com/product/4207

**Comment by madhephaestus** [comment]
Measure the distance with a caliper, make sure that the exact height we need exists. if so, the solderable ones look good.

**Comment by acamilo** [comment]
We will use the solder-able standoff.
