### ISSUE TITLE
pin 0 -- pullup or not?

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RobotInterfaceBoard#22]
Does pin 0 have an external pullup? It seems to make no difference whether I declare it as INPUT or INPUT_PULLUP. For reference, I want to use it as user interface (eg, to start counting).

**Comment by madhephaestus** [comment]
it does not have a pullup, *BUT* on normal boot it is set to INPUT_PULLUP, however on a reset it doesnt go through the same code and will come up without the pullup. It is always best practice to use the pullup explicitly.
