### ISSUE TITLE
Update power system for RIB

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/RobotInterfaceBoard#3]
Update of rib need not maintain the board outline nor bolt pattern. Use the check boxes to keep track of progress. 
@acamilo 

- [x] Bolt holes should be 5.5mm diameter, keepaway of 9mm diameter
- [x] Bolt holes should lie on a 25mm grid
- [x] Add a rail, one unit inboard of the Devkit-c, to allow the narrow version of the module to be used
- [x] 7.5 - 18 v battery in, with a solder lug and 
- [x] banana plug for power and ground (RAW)
- [ ] Side of board with the banana plugs should be ~80mm, with the bolt holes at 75mm center-to-center
- [x] A 5v 2 amp switching converter, RAW (post fuse) in ,  powering the ESP (SYSTEM 5)
- [x] 2 x external power converter ports, RAW (post fuse) in , regulated out, connectors to match the OTS switch mode we use (EXT REG)
- [x] 3.3v, 2 amp sensor power, replace the 3.3 from ESP pins (SENSOR 3.3) 
- [x] replace the 3.3 from ESP pins with SENSOR 3.3
- [x] both rails should have a power switch jumper bank, from rail to: SYSTEM 5,RAW,EXT REG,SENSOR 3.3
- [ ] each power bank should have an indicator led for each 4 power rails, total 8 leds, physically close to the associated rail.
- [ ] New Images, use the same names to keep documentation links consistent
- [x] connect GPIO 0 (BOOT) to the IO 
- [x] connect RST to IO
- [x] add a 5v level shiftier to i2c and expose the 5v side in a header
- [x] add 5v level shifted (bi directional) versions of 19,18,17,16,25,14
- [x] 5v bank should be similar to io bank, 8x3 0.1 in female headers, signel,  (SYSTEM 5), ground
- [ ] add SS on the outer edge of the IO, improve readability

**Comment by madhephaestus** [comment]
@acamilo please use this issue number in your commit messages to link them here

**Comment by acamilo** [comment]
- [ ] 7/2/2019 Send prototype to pcb house
- [ ] 7/9/2019 Begin assembly, testing, bugfixes
- [ ] 7/16/2019 Send out next rev
- [ ] 7/23/2019 assy,testing rev2
- [ ] 7/30/2019 start full turn order of 30

**Comment by acamilo** [comment]
each power bank should have an indicator led for each 4 power rails, total 8 leds, physically close to the associated rail.

Why do we need a power indicator for each rail and each voltage?

**Comment by madhephaestus** [comment]
@acamilo the power indicators were asked for specifically.
