### ISSUE TITLE
BEC headers should match the BEC

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/RobotInterfaceBoard#8]
on header should be 2 pin keyed female, the other a 3 pin male.

**Comment by acamilo** [comment]
I can not source the 2 pin keyed connectors.

**Comment by madhephaestus** [comment]
https://www.pololu.com/product/2181

**Comment by madhephaestus** [comment]
also https://www.digikey.com/catalog/en/partgroup/rcy-series/25502

**Comment by acamilo** [comment]
Free hanging, goes on the end of a cable.

**Comment by acamilo** [comment]
Also, the 2181 is a "male" but it is the end thats on the UBEC side.

**Comment by acamilo** [comment]
i recomend an adapter cable to something sensable.

**Comment by acamilo** [comment]
![image](https://user-images.githubusercontent.com/2826967/67122160-2e54d280-f1bb-11e9-9834-6c42d2c52c55.png)
like this JST

**Comment by acamilo** [comment]
I move forward with a PTH JST style connector and you have some students make and heat shrink a few short cables.

**Comment by madhephaestus** [comment]
just leave unpopulated and we can solder one of these on: https://www.pololu.com/product/2180

**Comment by acamilo** [comment]
I don't like danglers

**Comment by acamilo** [comment]
If we're going with a dangler then this issue is closed.
